apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: sample-app
    repoURL: https://github.com/your-repo/sample-app.git
    targetRevision: HEAD